name: "siplib.io"
description: ""

domain: aboutsip.github.com
author: Jonas Borjesson
email: jonas@aboutsip.com
title: siplib.io
sipstackio_version: 0.1.1
pktsio_version: 2.0.0

url: "http://localhost:4000"

markdown: rdiscount
permalink: pretty
highlighter: pygments
